In [17]:
# Como convenção importaremos a biblioteca numpy como np
import numpy as np

In [18]:
# EXERCICIO
# Crie uma array numpy com os valores 1, 2, 3
arraySimples = np.array ([1,2,3])
# Faça o produto escalar multiplicando a array por 5
vezesCinco = arraySimples*5
print arraySimples
print vezesCinco

[1 2 3]
[ 5 10 15]


In [19]:

# TESTE do exercício (2a)
assert np.all(vezesCinco == [5, 10, 15]), 'valor incorreto para vezesCinco'
print "Correto!"

Correto!


In [20]:
# EXERCICIO
# A função np.arange(inicio,fim,passo)  cria uma lista iniciando em inicio, terminando antes do fim seguindo passo
u = np.arange(0, 5, .5)   # np.array([0,0.5,1.0,...,4.5])
v = np.arange(5, 10, .5)

elementoAelemento = u*v
prodInterno = np.dot(u,v)
print 'u: {0}'.format(u)
print 'v: {0}'.format(v)
print '\nelementoAelemento\n{0}'.format(elementoAelemento)
print '\nprodInterno\n{0}'.format(prodInterno)

u: [ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5]
v: [ 5.   5.5  6.   6.5  7.   7.5  8.   8.5  9.   9.5]

elementoAelemento
[  0.     2.75   6.     9.75  14.    18.75  24.    29.75  36.    42.75]

prodInterno
183.75


In [21]:

# TESTE do exercício (2b)
assert np.all(elementoAelemento == [ 0., 2.75, 6., 9.75, 14., 18.75, 24., 29.75, 36., 42.75]), "Valores incorretos para elementoAelemento"
print "Primeiro teste OK"
assert prodInterno==183.75, "Valor incorreto para prodInterno"
print "Segundo teste OK"

Primeiro teste OK
Segundo teste OK


In [24]:
# EXERCICIO
from numpy.linalg import inv  # agora podemos utilizar o comando inv() sem preceder com np.linalg

# Criar uma matriz com listas de listas
A = np.matrix([[1,2,3,4],[5,6,7,8]])
print 'A:\n{0}'.format(A)

# Imprima a matriz transposta
B = np.matrix.transpose(A)
print '\nA transposta:\n{0}'.format(B)

# Multiplique A por sua Transposta
AAt = A*B
print '\nAAt:\n{0}'.format(AAt)

# Inverta AAt com o comando inv()
AAtInv = inv(AAt)
print '\nAAtInv:\n{0}'.format(AAtInv)

# Mostre que a matriz vezes sua inversa é a identidade
# .round(n) arredonda os valores para n casas decimais
print '\nAAtInv * AAt:\n{0}'.format((AAtInv * AAt).round(4))

A:
[[1 2 3 4]
 [5 6 7 8]]

A transposta:
[[1 5]
 [2 6]
 [3 7]
 [4 8]]

AAt:
[[ 30  70]
 [ 70 174]]

AAtInv:
[[ 0.54375 -0.21875]
 [-0.21875  0.09375]]

AAtInv * AAt:
[[ 1.  0.]
 [ 0.  1.]]


In [25]:
# TESTE do exercício (2c)
assert np.all(AAt == np.matrix([[30, 70], [70, 174]])), "Valores incorretos para AAt"
print "Primeiro teste OK"
assert np.allclose(AAtInv, np.matrix([[0.54375, -0.21875], [-0.21875, 0.09375]])), "Valor incorreto para AAtInv"
print "Segundo teste OK"

Primeiro teste OK
Segundo teste OK


In [28]:
# EXERCICIO
atributos = np.array([1, 2, 3, 4])
print 'atributos:\n{0}'.format(atributos)

# Crie uma array com os 3 últimos elementos de atributos
ultTres = atributos[-3: ]

print '\nÚltimos três:\n{0}'.format(ultTres)

atributos:
[1 2 3 4]

Últimos três:
[2 3 4]


In [29]:
# TEST do exercício (2d)
assert np.all(ultTres == [2, 3, 4]), "Valores incorretos para ultTres"
print "Teste OK"

Teste OK


In [30]:

# EXERCICIO
# Lembre-se que: "lambda x, y: x + y" cria uma função que adiciona dois valores
mult10 = lambda x : x*10
print mult10(5)

# Note that the function still shows its name as <lambda>
print '\n', mult10

50

<function <lambda> at 0x0000000006D93128>


In [31]:
assert mult10(10)==100, "Função incorreta"
print "Teste OK"

Teste OK


In [59]:

# EXERCICIO

# Escreva uma função Soma(x) que retorna uma função que recebe um valor y e soma ao x.
def Soma(x):
    def f(y):
        return x+y
    return f
 
Soma2 = lambda a,b: Soma(a)(b)
Soma3 = lambda a,b,c: Soma(Soma(a)(b))(c)

print Soma2(1,3), Soma3(1,2,3)



4 6


In [63]:
assert Soma3(1,2,3)==6, "Erro na função"
print "Ok"

Ok


In [66]:
class FuncionalW(object):
    def __init__(self, data):
        self.data = data
    def map(self, function):
        """Call `map` on the items in `data` using the provided `function`"""
        return FuncionalW(map(function, self.data))
    def reduce(self, function):
        """Call `reduce` on the items in `data` using the provided `function`"""
        return reduce(function, self.data)
    def filter(self, function):
        """Call `filter` on the items in `data` using the provided `function`"""
        return FuncionalW(filter(function, self.data))
    def __eq__(self, other):
        return (isinstance(other, self.__class__)
            and self.__dict__ == other.__dict__)
    def __getattr__(self, name):  return getattr(self.data, name)
    def __getitem__(self, k):  return self.data.__getitem__(k)
    def __repr__(self):  return 'FuncionalW({0})'.format(repr(self.data))
    def __str__(self):  return 'FuncionalW({0})'.format(str(self.data))

In [74]:
# EXERCICIO

dataset = FuncionalW(range(10))

# Multiplique cada elemento por 5
mult5= lambda x: x*5
mapResult = dataset.map(mult5)
# Filtre eliminando os elementos ímpares
# No Python "x % 2" é o resultado do resto da divisão de x por 2
pares= lambda x : (x%2==0)
filterResult = dataset.filter(pares)
# Some os elementos
soma = lambda x,y : x+y
reduceResult = dataset.reduce(soma)

print 'mapResult: {0}'.format(mapResult)
print '\nfilterResult: {0}'.format(filterResult)
print '\nreduceResult: {0}'.format(reduceResult)

mapResult: FuncionalW([0, 5, 10, 15, 20, 25, 30, 35, 40, 45])

filterResult: FuncionalW([0, 2, 4, 6, 8])

reduceResult: 45


In [75]:
assert mapResult == FuncionalW([0, 5, 10, 15, 20, 25, 30, 35, 40, 45]),"Valor incorreto para mapResult"
print "Teste 1 OK"

assert filterResult == FuncionalW([0, 2, 4, 6, 8]), "Valor incorreto para filterResult"
print "Teste 2 OK"

assert reduceResult == 45, "Valor incorreto para reduceResult"
print "Teste 3 OK"

Teste 1 OK
Teste 2 OK
Teste 3 OK


In [164]:
# EXERCICIO

# split() divide a string em palavras
Texto = FuncionalW("Esse texto tem varias palavras cada linha tem palavras escritas Esse texto esta escrito".split())

# Vamos fazer uma contagem da palavra 'palavras' no texto

# Crie uma função lambda que recebe duas entradas e retorna se são iguais ou não

Igual = lambda x,y: (x==y)
    
# Crie uma função lambda que utiliza a função Igual para detectar se a entrada é igual a palavra 'palavras'
DetectaPalavra = lambda x : Igual (x,'palavras')

# 1) Filtre as palavras iguais a 'palavras'
# 2) Mapeie todos os elementos para o valor 1
# 3) Reduza para a somatória
contagem = (Texto
           .filter (DetectaPalavra)
            .map (lambda x:1)
            .reduce (lambda x,y: x+y)
            )

print "Existem {} ocorrências de 'palavras'".format(contagem)





Existem 2 ocorrências de 'palavras'
